server:
  port: 8888

mycar:
  brand: BYD
  price: 100000

person:
#  username: "李四 \n 张三"     # 双引号会输出换行
  username: '李四 \n 张三'      # 单引号会输出字符串\n
  boss: true
  birth: 2022/02/13
  age: 18
#  interests: [篮球， 足球]
  interests:
    - 篮球
    - 足球
    - 18
  animals: [阿猫, 阿狗s]
  score:
    english: 80
    math: 90
  salaries:
    - 9999.98
    - 9999.92
  pet:
    name: 阿狗
    weight: 99.99
  allPets:
     sick:
       - {name: Tom, weight: 88.88}
       - {name: Jerry, weight: 77.77}
       - name: King
         weight: 99.99
     health:
       - {name: Rose, weight: 66.66}
       - {name: Jack, weight: 55.55}

#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: classpath:/haha/
spring:
  web:
    resources:
#      add-mappings: false   # 禁用静态资源
      add-mappings: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3316/db_yeb
    username: yeb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
    # 以下为整合Druid数据源配置，使用druid-spring-boot-starter
    druid:
      stat-view-servlet:      # Web监控页面 http://localhost:8888/druid/
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: true
#      web-stat:
#        enabled: true
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#        url-patterns: /*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: cn.geekhall.sbdemo  # Spring 监控 AOP 切入点，监控SpringBean 。如 x.y.z.service.*， 配置多个英文逗号分隔。
      filters: stat, wall

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          db-type: mysql
          config:
            drop-table-allow: false

  jdbc:
    template:
      query-timeout: 3
  redis:
#    url: redis://127.0.0.1:6379
    host: 127.0.0.1
    port: 6379
    client-type: lettuce  # or jedis
    lettuce:
      pool:
        max-active: 10
        min-idle: 4
  boot:
    admin:
      client:
        url: http://localhost:8899
#        instance:
#          prefer-ip: true  # 过时
  application:
    name: sbdemo

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml # 不使用mybatis-config.xml中的内容，打开会报错。
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# http://localhost:8888/actuator/
management:
  endpoints:
    enabled-by-default: true  # 默认开启所有监控端点
    web:
      exposure:
        include: '*'    # 以Web方式暴露所有监控端点。

  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true



info:
  appName: sbdemo
  appVersion: 1.0.0
  mavenProjectName: @project.name@        # 使用@variable@的方式获得maven的pom文件中的信息
  mavenProjectVersion: @project.version@
