server:
  port: 8888

mycar:
  brand: BYD
  price: 100000

person:
#  username: "李四 \n 张三"     # 双引号会输出换行
  username: '李四 \n 张三'      # 单引号会输出字符串\n
  boss: true
  birth: 2022/02/13
  age: 18
#  interests: [篮球， 足球]
  interests:
    - 篮球
    - 足球
    - 18
  animals: [阿猫, 阿狗s]
  score:
    english: 80
    math: 90
  salaries:
    - 9999.98
    - 9999.92
  pet:
    name: 阿狗
    weight: 99.99
  allPets:
     sick:
       - {name: Tom, weight: 88.88}
       - {name: Jerry, weight: 77.77}
       - name: King
         weight: 99.99
     health:
       - {name: Rose, weight: 66.66}
       - {name: Jack, weight: 55.55}

#spring:
#  mvc:
#    static-path-pattern: /res/**
#  web:
#    resources:
#      static-locations: classpath:/haha/
spring:
  web:
    resources:
#      add-mappings: false   # 禁用静态资源
      add-mappings: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
